In [1]:
from ipynb.fs.full.metrics import get_performance_df_v2

## Case 1

In [11]:
case = 'Case1'
bfname = f'100K_{case}'
nstreams = 15
df = get_performance_df_v2(n_streams=nstreams, 
                          bfname = bfname, 
                          gt_folder = '/home/epanjei/Codes/OutlierGen/exos/cases',
                          rel_path =  f'pickles/cases/{case}',
                          performance_folder = 'pickles/performance/cases',
                          n_experiments=10,
                          window_size=1000,
                          non_data_attr=2,
                          vcase=case)
df

   experiment  precision    recall  f1_score  running_time
0           1   0.832672  0.641262  0.655578     77.238114
1           2   0.836402  0.646769  0.662295     76.496487
2           3   0.842782  0.644403  0.664932     76.382331
3           4   0.840783  0.650636  0.666535     76.992946
4           5   0.835671  0.630100  0.655552     77.294268
5           6   0.843010  0.646938  0.665372     78.063134
6           7   0.846668  0.653891  0.669129     78.175082
7           8   0.816335  0.646381  0.648234     77.388737
8           9   0.831214  0.637275  0.654572     77.119028
9          10   0.836770  0.634112  0.654571     76.774857

## Case 2

In [12]:
case = 'Case2'
bfname = f'100K_{case}'
nstreams = 15
df = get_performance_df_v2(n_streams=nstreams, 
                          bfname = bfname, 
                          gt_folder = '/home/epanjei/Codes/OutlierGen/exos/cases',
                          rel_path =  f'pickles/cases/{case}',
                          performance_folder = 'pickles/performance/cases',
                          n_experiments=10,
                          window_size=1000,
                          non_data_attr=2,
                          vcase=case)
df

   experiment  precision    recall  f1_score  running_time
0           1   0.851411  0.653806  0.673159     76.689415
1           2   0.850055  0.639549  0.666645     76.970902
2           3   0.847466  0.629960  0.659725     77.139776
3           4   0.861718  0.661395  0.682383     76.492010
4           5   0.836146  0.621239  0.651408     78.581087
5           6   0.843479  0.658047  0.670329     78.176722
6           7   0.858029  0.662422  0.679938     77.628457
7           8   0.863465  0.651514  0.680436     77.580711
8           9   0.829617  0.645458  0.655739     77.293980
9          10   0.866577  0.654989  0.683008     78.590610

## Case 3

In [13]:
case = 'Case3'
bfname = f'100K_{case}'
nstreams = 15
df = get_performance_df_v2(n_streams=nstreams, 
                          bfname = bfname, 
                          gt_folder = '/home/epanjei/Codes/OutlierGen/exos/cases',
                          rel_path =  f'pickles/cases/{case}',
                          performance_folder = 'pickles/performance/cases',
                          n_experiments=10,
                          window_size=1000,
                          non_data_attr=2,
                          vcase=case)
df

   experiment  precision    recall  f1_score  running_time
0           1   0.856743  0.642319  0.672189     76.915216
1           2   0.838326  0.643120  0.658059     77.365978
2           3   0.854801  0.647785  0.670847     76.742184
3           4   0.839797  0.647079  0.663759     77.734093
4           5   0.853201  0.652002  0.672618     77.749632
5           6   0.855013  0.654190  0.671449     77.302566
6           7   0.835923  0.634110  0.654392     77.004437
7           8   0.854120  0.642431  0.670755     76.761148
8           9   0.853442  0.644846  0.667836     77.203699
9          10   0.858050  0.656815  0.675552     76.985728

In [14]:
## Case 4

In [16]:
case = 'Case4'
bfname = f'100K_{case}'
nstreams = 15
df = get_performance_df_v2(n_streams=nstreams, 
                          bfname = bfname, 
                          gt_folder = '/home/epanjei/Codes/OutlierGen/exos/cases',
                          rel_path =  f'pickles/cases/{case}',
                          performance_folder = 'pickles/performance/cases',
                          n_experiments=10,
                          window_size=1000,
                          non_data_attr=2,
                          vcase=case)
df

   experiment  precision    recall  f1_score  running_time
0           1   0.860897  0.650131  0.677060     77.806310
1           2   0.840709  0.642400  0.661453     78.503521
2           3   0.843208  0.658689  0.668777     77.453366
3           4   0.846929  0.660290  0.673251     78.511428
4           5   0.842288  0.653748  0.665239     78.078966
5           6   0.862254  0.664631  0.685835     78.723108
6           7   0.850210  0.647916  0.667614     78.387503
7           8   0.852488  0.661147  0.677285     78.833967
8           9   0.860985  0.656693  0.680318     76.671640
9          10   0.857679  0.654427  0.676938     77.534073